export const API_CALL = "API_CALL"
export const API_FAILS = "API_FAILS"
export const GET_INFO = "GET_INFO"
export const SEARCH_EVE = "SEARCH_EVE"
export const COUNTRY = "COUNTRY"
export const GENRE = "GENRE"
